In [1]:
import numpy as np

## Intermezzo

In [2]:
!ls

data  numpy-intro.ipynb  numpy-more-exciting.ipynb


In [3]:
!pwd

/home/lachlan/my_phd/courses/pp4rs/playground/python-numpy


In [4]:
!ls data/

collect_weather_data.R	LAUST010000000000003.csv  mrw_data  zrh_weather.txt


In [5]:
!ls data/mrw_data/

intermediate.csv	 mrw.csv     nonoil_school.csv	oecd_school.csv
intermediate_school.csv  nonoil.csv  oecd.csv


In [6]:
!head data/mrw_data/nonoil.csv

rgdpw60,rgdpw85,gdpgrowth,popgrowth,i_y
2485.0,4371.0,4.8,2.6,24.1
1588.0,1171.0,0.8,2.1,5.8
1116.0,1071.0,2.2,2.4,10.8
959.0,3671.0,8.6,3.2,28.3
529.0,857.0,2.9,0.9,12.7
755.0,663.0,1.2,1.7,5.1
889.0,2190.0,5.7,2.1,12.8
838.0,789.0,1.5,1.7,10.5
908.0,462.0,-0.9,1.9,6.9


In [7]:
nonoil = np.genfromtxt('data/mrw_data/nonoil.csv', delimiter = ',',
                      skip_header = 1)

In [8]:
nonoil

array([[ 2.4850e+03,  4.3710e+03,  4.8000e+00,  2.6000e+00,  2.4100e+01],
       [ 1.5880e+03,  1.1710e+03,  8.0000e-01,  2.1000e+00,  5.8000e+00],
       [ 1.1160e+03,  1.0710e+03,  2.2000e+00,  2.4000e+00,  1.0800e+01],
       [ 9.5900e+02,  3.6710e+03,  8.6000e+00,  3.2000e+00,  2.8300e+01],
       [ 5.2900e+02,  8.5700e+02,  2.9000e+00,  9.0000e-01,  1.2700e+01],
       [ 7.5500e+02,  6.6300e+02,  1.2000e+00,  1.7000e+00,  5.1000e+00],
       [ 8.8900e+02,  2.1900e+03,  5.7000e+00,  2.1000e+00,  1.2800e+01],
       [ 8.3800e+02,  7.8900e+02,  1.5000e+00,  1.7000e+00,  1.0500e+01],
       [ 9.0800e+02,  4.6200e+02, -9.0000e-01,  1.9000e+00,  6.9000e+00],
       [ 1.0090e+03,  2.6240e+03,  6.2000e+00,  2.4000e+00,  2.8800e+01],
       [ 9.0700e+02,  2.1600e+03,  6.0000e+00,  2.5000e+00,  1.6300e+01],
       [ 5.3300e+02,  6.0800e+02,  2.8000e+00,  2.3000e+00,  5.4000e+00],
       [ 1.0090e+03,  7.2700e+02,  1.0000e+00,  2.3000e+00,  9.1000e+00],
       [ 1.3860e+03,  1.7040e+03,  5.1

In [9]:
nonoil = np.genfromtxt('data/mrw_data/nonoil.csv', delimiter = ',',
                      names = True)

In [10]:
nonoil[0:3]

array([(2485., 4371., 4.8, 2.6, 24.1), (1588., 1171., 0.8, 2.1,  5.8),
       (1116., 1071., 2.2, 2.4, 10.8)],
      dtype=[('rgdpw60', '<f8'), ('rgdpw85', '<f8'), ('gdpgrowth', '<f8'), ('popgrowth', '<f8'), ('i_y', '<f8')])

In [11]:
nonoil['i_y']

array([24.1,  5.8, 10.8, 28.3, 12.7,  5.1, 12.8, 10.5,  6.9, 28.8, 16.3,
        5.4,  9.1, 12.4, 17.4, 21.5,  7.1, 13.2,  7.3, 25.6, 17.1,  8.3,
        6.1, 10.3, 12. ,  7.9,  9.6, 10.9, 13.8, 21.6, 13.2, 18. , 15.5,
       13.8,  4.1,  6.5, 31.7, 21.1,  6.8, 11.4, 19.9, 16.8, 28.5, 36. ,
       17.6, 22.3, 23.2,  5.9, 12.2, 14.9, 32.2, 14.8, 15.9, 18. , 23.4,
       23.4, 26.6, 36.9, 26.2, 28.5, 29.3, 25.9, 24.9, 25.8, 29.1, 22.5,
       17.7, 24.5, 29.7, 20.2, 18.4, 23.3, 14.7, 17.1,  8. ,  8.8,  7.1,
       13.8, 20.6, 19.5, 14.5, 26.1, 20.4, 21.1, 25.3, 13.3, 23.2, 29.7,
       18. , 24.4, 11.7, 12. , 11.8, 11.4, 31.5, 13.9, 22.5, 16.2])

In [12]:
type(nonoil)

numpy.ndarray

In [13]:
nonoil.shape

(98,)

#  Functions of arrays

In [14]:
log_gdp_85 = np.log(nonoil['rgdpw85'])

In [15]:
log_gdp_85

array([8.38274709, 7.06561336, 6.97634807, 8.20821938, 6.75343792,
       6.49677499, 7.69165682, 6.67076632, 6.13556489, 7.87245515,
       7.6778635 , 6.41017488, 6.58892648, 7.44073371, 7.19218206,
       6.85012617, 6.88243747, 6.7129562 , 6.56526497, 6.94505106,
       7.99530662, 7.76131918, 6.94215671, 6.73459166, 7.07834158,
       6.54534966, 7.27931884, 6.69084228, 6.48768402, 8.86276674,
       6.94505106, 6.56526497, 6.88550967, 8.20549161, 6.50279005,
       6.02102335, 7.10414409, 7.65302041, 7.10742547, 6.93828448,
       9.50091825, 7.19967835, 9.25435726, 9.5391404 , 8.36915711,
       8.47114925, 8.66354209, 6.8814113 , 7.68478394, 7.79564654,
       9.59410505, 7.81681997, 8.70649036, 8.07713664, 9.49754733,
       9.56731527, 9.71057006, 9.53090097, 9.61760386, 9.63541201,
       8.83462822, 9.0682006 , 9.31307745, 9.48622816, 9.88954075,
       8.67025757, 9.20059302, 9.63148196, 9.67287871, 8.39931015,
       9.49784743, 9.79450939, 8.41005332, 8.10409906, 7.59940

In [16]:
log_gdp_85.shape

(98,)

In [17]:
log_i_y = np.log(nonoil['i_y'] / 100)

In [18]:
log_popgrowth = np.log(nonoil['popgrowth'] / 100 + 0.05)

In [19]:
iota = np.ones_like(log_i_y)

In [20]:
iota.shape

(98,)

In [21]:
iota.shape == log_i_y.shape

True

In [22]:
X = np.stack([iota, log_i_y, log_popgrowth], axis = 1)

In [23]:
X.shape

(98, 3)

In [24]:
y = log_gdp_85

# array operations

In [25]:
# transposes
X.T

array([[ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1. 

In [26]:
# matrix multiplication

X.T @ y

array([  788.69523114, -1418.73302646, -2087.18508137])

In [27]:
y2 = y[:, np.newaxis]

In [28]:
y2.shape

(98, 1)

In [29]:
np.matmul(X.T, y2)

array([[  788.69523114],
       [-1418.73302646],
       [-2087.18508137]])

In [30]:
np.linalg.inv(X.T @ X)   # real inverse

array([[5.28352259, 0.20707318, 1.85315507],
       [0.20707318, 0.04313087, 0.04824796],
       [1.85315507, 0.04824796, 0.66841862]])

In [31]:
import scipy.linalg as la

In [32]:
la.pinv2(X.T @ X)

array([[5.28352259, 0.20707318, 1.85315508],
       [0.20707318, 0.04313087, 0.04824796],
       [1.85315507, 0.04824796, 0.66841862]])

In [33]:
beta_ols = (la.pinv2(X.T @ X)) @ (X.T @ y2)

In [34]:
beta_ols

array([[ 5.4298831 ],
       [ 1.42401428],
       [-1.98977448]])

## Challenge

1. write a function import_mrw() that imports either nonoil.csv, intermediate.csv or oecd.csv so that

my_data = import_mrw(path, dataset) 

imports the data,

i.e. import_mrw(path = 'data/mrw_data', dataset = nonoil)

imports the nonoil data and so on

2. write a function that takes the original data and creates the X and y variables needed for regression. so that function I want is something like

y, X = create_matrices(dataset, mankiws_constant)

where mankiws_constant defaults to 0.05

3. write a function ols_coeff(X, y) that returns OLS coefficients 

4. modify import_mrw so that it can append the *_school.csv data during the import with an option 'add_school = True'


In [45]:
# q 1
def import_mrw(path, dataset):
    
    data_subsets = ['nonoil', 'intermediate', 'oecd']
    
    assert dataset in data_subsets 
    
    return np.genfromtxt((path + '/' + dataset + '.csv'), delimiter= ',',
                         names = True)

In [46]:
my_path = 'data/mrw_data'
data = 'africa'

In [47]:
oecd = import_mrw(my_path, data)

AssertionError: 

In [51]:
# q2

def create_matrices(dataset, mankiws_constant = 0.05):
    
    # y
    log_gdp_85 = np.log(dataset['rgdpw85'])
    
    # x vars
    iota = np.ones_like(log_gdp_85)
    log_i_y = np.log(dataset['i_y'] / 100)
    log_popgrowth = np.log(dataset['popgrowth'] / 100 + mankiws_constant)
    
    # stacks Xs 
    X = np.stack([iota, log_i_y, log_popgrowth], axis = 1)
    
    return log_gdp_85, X
    
    
    
    

In [53]:
y1, x1 = create_matrices(oecd)

In [54]:
y2, x2 = create_matrices(oecd, mankiws_constant= 0.05)

In [55]:
y3, x3 = create_matrices(oecd, mankiws_constant= 0.07)

In [57]:
def ols_coeff(y, X):
    
    beta_ols = (np.linalg.inv(X.T @ X)) @ (X.T @ y) 
    
    return beta_ols

In [58]:
oecd_beta = ols_coeff(y1, x1)

In [59]:
oecd_beta

array([ 8.02060676,  0.49988954, -0.74192146])

In [75]:
# q4 

def import_mrw2(path, dataset, school = True):
    
    data_subsets = ['nonoil', 'intermediate', 'oecd']
    
    assert dataset in data_subsets 
    
    base_data = np.genfromtxt((path + '/' + dataset + '.csv'), delimiter= ',',
                         names = True)
    
    if school == True:
        school_fp = path + '/' + dataset + '_school'  + '.csv'
        school_data = np.genfromtxt(school_fp, names = ['school'])
        
        base_data = np.stack([base_data, school_data], axis = 1)
        
    return base_data
        

In [76]:
oecd2 = import_mrw2('data/mrw_data/', dataset = 'oecd', school = True)



TypeError: invalid type promotion

In [62]:
school_data

array([(10.9,), ( 8. ,), ( 9.3,), (10.7,), (11.5,), ( 8.9,), ( 8.4,),
       ( 7.9,), (11.4,), ( 7.1,), (10.7,), (10. ,), ( 5.8,), ( 8. ,),
       ( 7.9,), ( 4.8,), ( 5.5,), ( 8.9,), (10.6,), (11.9,), ( 9.8,),
       (11.9,)], dtype=[('school', '<f8')])

In [60]:
!head data/mrw_data/oecd_school.csv

10.9
8.0
9.3
10.7
11.5
8.9
8.4
7.9
11.4
7.1
