In [1]:
import numpy as np

In [2]:
np.__version__

'1.17.2'

## Create Arrays

In [3]:
num_list = list(range(10))

In [4]:
num_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
type(num_list)

list

In [6]:
my_array = np.array(num_list)

In [7]:
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
type(my_array)

numpy.ndarray

In [9]:
my_array2 = np.array([2.3, 4.6, 3.14])

In [10]:
my_array2

array([2.3 , 4.6 , 3.14])

In [11]:
my_array.dtype

dtype('int64')

In [12]:
my_array2.dtype

dtype('float64')

In [13]:
my_float_array = my_array.astype('float64')

In [14]:
my_float_array

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [15]:
my_float_array.dtype

dtype('float64')

In [16]:
my_string_array = my_array.astype('str')

In [17]:
my_string_array.dtype

dtype('<U21')

In [18]:
my_string_array

array(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U21')

In [19]:
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
my_array3 = np.array([2.4, 'hello'])

In [21]:
my_array3.dtype

dtype('<U32')

In [22]:
my_array3

array(['2.4', 'hello'], dtype='<U32')

## 'Special' Arrays

In [23]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
np.empty(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
np.zeros(10) == np.empty(10)

array([False, False, False, False, False, False, False, False, False,
       False])

In [26]:
np.empty(1)[0]

0.0

In [27]:
np.array_equal(np.zeros(10), np.empty(10)) 

True

In [28]:
np.empty(3)[1]

4.6

In [31]:
my_ones = np.ones(10)

In [32]:
np.empty_like(my_ones)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [33]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [34]:
np.full((3,5), 4)

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [35]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [36]:
np.arange(0,10, step =0.2)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ,
       5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6,
       7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8])

In [37]:
np.linspace(0,10, endpoint = True )

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [39]:
np.linspace(0,10, endpoint = True, num = 51)

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
        2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,
        4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,
        6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,
        8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. ])

In [40]:
np.logspace(0, 4, num = 10)

array([1.00000000e+00, 2.78255940e+00, 7.74263683e+00, 2.15443469e+01,
       5.99484250e+01, 1.66810054e+02, 4.64158883e+02, 1.29154967e+03,
       3.59381366e+03, 1.00000000e+04])

In [41]:
help(np.logspace)

Help on function logspace in module numpy:

logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None, axis=0)
    Return numbers spaced evenly on a log scale.
    
    In linear space, the sequence starts at ``base ** start``
    (`base` to the power of `start`) and ends with ``base ** stop``
    (see `endpoint` below).
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    Parameters
    ----------
    start : array_like
        ``base ** start`` is the starting value of the sequence.
    stop : array_like
        ``base ** stop`` is the final value of the sequence, unless `endpoint`
        is False.  In that case, ``num + 1`` values are spaced over the
        interval in log-space, of which all but the last (a sequence of
        length `num`) are returned.
    num : integer, optional
        Number of samples to generate.  Default is 50.
    endpoint : boolean, optional
        If true, `stop` is the last sample. Otherwise, 

In [42]:
np.random.random(5)

array([0.39639178, 0.93428043, 0.78741492, 0.83250205, 0.85438502])

In [44]:
np.random.random((3,3))

array([[0.03235301, 0.12380782, 0.70083359],
       [0.19069252, 0.12942088, 0.83418534],
       [0.78677079, 0.88684725, 0.5368337 ]])

In [45]:
np.random.randint(0, 10, (3,4))

array([[6, 3, 2, 5],
       [1, 9, 2, 4],
       [9, 3, 1, 4]])

In [46]:
np.random.normal(loc = 0, scale = 3, size = (3,3))

array([[ 2.49200119,  1.4026518 , -0.16573412],
       [ 1.50678581,  1.51698823,  5.03217095],
       [ 0.95275918, -2.16672175,  6.13112076]])

In [48]:
help(np.random.normal)

Help on built-in function normal:

normal(...) method of numpy.random.mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution.
    scale : float or array_like of floats
        Standard deviation (spread or "width") of the distribution. Must be
        non-negative.
    size : int or 

In [49]:
import numpy.random as npr

In [50]:
npr.random(10)

array([0.85710999, 0.70492785, 0.17216592, 0.9713727 , 0.67533873,
       0.82959871, 0.26423925, 0.17148261, 0.47053528, 0.56248855])

In [51]:
np.random.seed(1234567890)

In [53]:
my_rand_array = np.random.normal(loc = 0, scale = 2, size = (5,5))

In [54]:
my_rand_array

array([[ 2.68032692,  3.47518246,  2.99797669, -0.45728666,  4.062068  ],
       [ 4.34064989,  3.1929053 , -1.53890311,  1.13211647, -0.23854036],
       [-0.29302161, -1.59780675,  1.54366556, -1.65638272,  2.65334965],
       [ 2.11973553,  4.28817745, -2.86929025,  4.57487309,  0.85729715],
       [-2.55471548, -1.62479612,  0.59776252, -1.66958802,  1.14469341]])

## attributes

In [55]:
my_rand_array.dtype

dtype('float64')

In [56]:
my_rand_array.ndim

2

In [57]:
my_rand_array.shape

(5, 5)

In [58]:
my_rand_array.size

25

In [60]:
my_rand_array.itemsize

8

In [62]:
my_rand_array.shape

(5, 5)

In [63]:
n_row = my_rand_array.shape[0]

In [64]:
n_col = my_rand_array.shape[1]

In [65]:
print(n_row)

5


In [66]:
print(n_col)

5


In [67]:
rows, cols = my_rand_array.shape

In [68]:
rows

5

In [69]:
cols

5

In [70]:
_ , cols2 = my_rand_array.shape

In [71]:
cols2

5

## array indexing

In [72]:
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
my_array[0]

0

In [75]:
my_array[1:3]

array([1, 2])

In [76]:
my_array[-1]

9

In [77]:
my_rand_array

array([[ 2.68032692,  3.47518246,  2.99797669, -0.45728666,  4.062068  ],
       [ 4.34064989,  3.1929053 , -1.53890311,  1.13211647, -0.23854036],
       [-0.29302161, -1.59780675,  1.54366556, -1.65638272,  2.65334965],
       [ 2.11973553,  4.28817745, -2.86929025,  4.57487309,  0.85729715],
       [-2.55471548, -1.62479612,  0.59776252, -1.66958802,  1.14469341]])

In [78]:
my_rand_array[0,1]

3.4751824554387216

In [79]:
my_rand_array[0, :]

array([ 2.68032692,  3.47518246,  2.99797669, -0.45728666,  4.062068  ])

In [80]:
my_rand_array[: , 1]

array([ 3.47518246,  3.1929053 , -1.59780675,  4.28817745, -1.62479612])

In [81]:
my_rand_array[: , 1].shape

(5,)

In [82]:
my_rand_array[: , 1].reshape(1,5)

array([[ 3.47518246,  3.1929053 , -1.59780675,  4.28817745, -1.62479612]])

In [83]:
my_rand_array[: , 1].reshape(5,1)  # hurrah!

array([[ 3.47518246],
       [ 3.1929053 ],
       [-1.59780675],
       [ 4.28817745],
       [-1.62479612]])

In [84]:
my_slice = my_rand_array[:, 1]

In [85]:
my_slice

array([ 3.47518246,  3.1929053 , -1.59780675,  4.28817745, -1.62479612])

In [87]:
my_slice[:, np.newaxis]

array([[ 3.47518246],
       [ 3.1929053 ],
       [-1.59780675],
       [ 4.28817745],
       [-1.62479612]])

In [88]:
my_slice[np.newaxis, :]

array([[ 3.47518246,  3.1929053 , -1.59780675,  4.28817745, -1.62479612]])

In [89]:
my_slice

array([ 3.47518246,  3.1929053 , -1.59780675,  4.28817745, -1.62479612])

In [90]:
my_col_slice = my_slice[:, np.newaxis]

In [91]:
my_col_slice

array([[ 3.47518246],
       [ 3.1929053 ],
       [-1.59780675],
       [ 4.28817745],
       [-1.62479612]])

In [92]:
my_col_slice.T

array([[ 3.47518246,  3.1929053 , -1.59780675,  4.28817745, -1.62479612]])

## Copies?

In [93]:
my_rand_array

array([[ 2.68032692,  3.47518246,  2.99797669, -0.45728666,  4.062068  ],
       [ 4.34064989,  3.1929053 , -1.53890311,  1.13211647, -0.23854036],
       [-0.29302161, -1.59780675,  1.54366556, -1.65638272,  2.65334965],
       [ 2.11973553,  4.28817745, -2.86929025,  4.57487309,  0.85729715],
       [-2.55471548, -1.62479612,  0.59776252, -1.66958802,  1.14469341]])

In [94]:
my_matrix = my_rand_array

In [95]:
my_matrix

array([[ 2.68032692,  3.47518246,  2.99797669, -0.45728666,  4.062068  ],
       [ 4.34064989,  3.1929053 , -1.53890311,  1.13211647, -0.23854036],
       [-0.29302161, -1.59780675,  1.54366556, -1.65638272,  2.65334965],
       [ 2.11973553,  4.28817745, -2.86929025,  4.57487309,  0.85729715],
       [-2.55471548, -1.62479612,  0.59776252, -1.66958802,  1.14469341]])

In [96]:
my_matrix[0, :] = 1

In [97]:
my_matrix

array([[ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ],
       [ 4.34064989,  3.1929053 , -1.53890311,  1.13211647, -0.23854036],
       [-0.29302161, -1.59780675,  1.54366556, -1.65638272,  2.65334965],
       [ 2.11973553,  4.28817745, -2.86929025,  4.57487309,  0.85729715],
       [-2.55471548, -1.62479612,  0.59776252, -1.66958802,  1.14469341]])

In [99]:
my_matrix[0, :] = [1,2,3]

ValueError: cannot copy sequence with size 3 to array axis with dimension 5

In [100]:
my_rand_array

array([[ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ],
       [ 4.34064989,  3.1929053 , -1.53890311,  1.13211647, -0.23854036],
       [-0.29302161, -1.59780675,  1.54366556, -1.65638272,  2.65334965],
       [ 2.11973553,  4.28817745, -2.86929025,  4.57487309,  0.85729715],
       [-2.55471548, -1.62479612,  0.59776252, -1.66958802,  1.14469341]])

In [101]:
my_other_matrix = my_rand_array.copy()

In [102]:
my_other_matrix

array([[ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ],
       [ 4.34064989,  3.1929053 , -1.53890311,  1.13211647, -0.23854036],
       [-0.29302161, -1.59780675,  1.54366556, -1.65638272,  2.65334965],
       [ 2.11973553,  4.28817745, -2.86929025,  4.57487309,  0.85729715],
       [-2.55471548, -1.62479612,  0.59776252, -1.66958802,  1.14469341]])

In [103]:
my_other_matrix[0, :] = 4

In [104]:
my_other_matrix

array([[ 4.        ,  4.        ,  4.        ,  4.        ,  4.        ],
       [ 4.34064989,  3.1929053 , -1.53890311,  1.13211647, -0.23854036],
       [-0.29302161, -1.59780675,  1.54366556, -1.65638272,  2.65334965],
       [ 2.11973553,  4.28817745, -2.86929025,  4.57487309,  0.85729715],
       [-2.55471548, -1.62479612,  0.59776252, -1.66958802,  1.14469341]])

In [105]:
my_rand_array

array([[ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ],
       [ 4.34064989,  3.1929053 , -1.53890311,  1.13211647, -0.23854036],
       [-0.29302161, -1.59780675,  1.54366556, -1.65638272,  2.65334965],
       [ 2.11973553,  4.28817745, -2.86929025,  4.57487309,  0.85729715],
       [-2.55471548, -1.62479612,  0.59776252, -1.66958802,  1.14469341]])